/// 场景构造方式。
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScenarioKind {
    LegacyCombo,
    ScoreSoloEv,
    ScoreAutoEv,
    ScoreCheerful,
    PowerNoev,
    Mysekai,
    ScoreFinalChapter,
    ScoreFixedCard,
    ScoreFixedChar,
    ScoreMultiEvDiffMusic,
}

/// 单个 scenario 定义。
#[derive(Clone, Copy, Debug)]
pub struct ScenarioDef {
    pub name: &'static str,
    pub source_combo: &'static str,
    pub kind: ScenarioKind,
    pub min_cases: usize,
    pub max_cases: Option<usize>,
    /// 单 case 性能阈值（毫秒），超过则判定为 Bug
    pub perf_limit_ms: f64,
}

pub const SCENARIOS: &[ScenarioDef] = &[
    // === Legacy combo (有 C++ reference_output 对比) ===
    ScenarioDef {
        name: "score_multi_ev",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 5,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_multi_noev",
        source_combo: "score_multi_noev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 5,
        max_cases: None,
        perf_limit_ms: 20.0,
    },
    ScenarioDef {
        name: "power_solo_ev",
        source_combo: "power_solo_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 5,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "skill_auto_ev",
        source_combo: "skill_auto_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 5,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    // === 变体 scenario (soundness 验证) ===
    ScenarioDef {
        name: "score_solo_ev_soundness",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::ScoreSoloEv,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_auto_ev_soundness",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::ScoreAutoEv,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_cheerful",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::ScoreCheerful,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "power_noev",
        source_combo: "power_solo_ev",
        kind: ScenarioKind::PowerNoev,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "mysekai",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::Mysekai,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 5.0,
    },
    // === 终章 (暂时放宽阈值) ===
    ScenarioDef {
        name: "score_final_chapter",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::ScoreFinalChapter,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 100.0,
    },
    // === 约束变体 ===
    ScenarioDef {
        name: "score_fixed_card",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::ScoreFixedCard,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_fixed_char",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::ScoreFixedChar,
        min_cases: 5,
        max_cases: Some(8),
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_multi_ev_diff_music",
        source_combo: "score_multi_ev",
        kind: ScenarioKind::ScoreMultiEvDiffMusic,
        min_cases: 5,
        max_cases: Some(10),
        perf_limit_ms: 5.0,
    },
    // === Comprehensive C++ reference_output combo ===
    ScenarioDef {
        name: "score_solo_ev",
        source_combo: "score_solo_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_solo_noev",
        source_combo: "score_solo_noev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_auto_ev",
        source_combo: "score_auto_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_auto_noev",
        source_combo: "score_auto_noev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "power_multi_ev",
        source_combo: "power_multi_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "power_multi_noev",
        source_combo: "power_multi_noev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "power_auto_ev",
        source_combo: "power_auto_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "power_solo_noev",
        source_combo: "power_solo_noev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "skill_solo_ev",
        source_combo: "skill_solo_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "skill_multi_ev",
        source_combo: "skill_multi_ev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "skill_multi_noev",
        source_combo: "skill_multi_noev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "skill_auto_noev",
        source_combo: "skill_auto_noev",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_challenge",
        source_combo: "score_challenge",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 10.0,
    },
    ScenarioDef {
        name: "score_multi_ev_fixed_card",
        source_combo: "score_multi_ev_fixed_card",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_multi_ev_fixed_char",
        source_combo: "score_multi_ev_fixed_char",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_multi_ev_excluded",
        source_combo: "score_multi_ev_excluded",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_multi_ev_unit_filter",
        source_combo: "score_multi_ev_unit_filter",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
    ScenarioDef {
        name: "score_multi_ev_teammate",
        source_combo: "score_multi_ev_teammate",
        kind: ScenarioKind::LegacyCombo,
        min_cases: 30,
        max_cases: None,
        perf_limit_ms: 5.0,
    },
];

pub fn get_scenario(name: &str) -> Option<&'static ScenarioDef> {
    SCENARIOS.iter().find(|scenario| scenario.name == name)
}
